#define SIGNALIZER_MAJOR 0
#define SIGNALIZER_MINOR 2
#define SIGNALIZER_BUILD 10
#define SIGNALIZER_BUILD_INFO "  dev\n  master\n* oscilloscope\n\n3e688dd\n"

#define SIGNALIZER_VERSION_STRING "0.2.10"
#define SIGNALIZER_VST_VERSION_HEX 0x00020a